# !/bin/bash

# Script para la corrección de los nombres de vías extraídos de Catastro por cat2osm
# Uso: sh corregir.sh nombre_municipio

Poblacion=$1
if [ $# -ne 1 ]; then
  echo "Script para la corrección de los nombres de vías extraídos de Catastro por cat2osm"
  echo "El archivo a corregir debe estar en result/MUNICIPIO."
  echo "Uso: `basename $0` MUNICIPIO"
  exit 1
fi
if [ -L "$0" ]; then
  cd "$( dirname "$( readlink "$0" )" )"
else
  cd "$( dirname "$0" )"
fi
cd ..
if [ ! -d "result/$municipio" ]; then
  echo "No existe result/$municipio"
  exit 2
fi
# sh scripts/extraer.sh $Poblacion
# nano config/config_$Poblacion
# /usr/lib/jvm/jdk1.7.0_03/jre/bin/java -jar cat2osm.jar config/config_$Poblacion -ejes
sed -i "/Adriatico/s/Adriatico/Adriático/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Aguila]/s/Aguila/Águila/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Agustin[ |\"|']/s/Agustin/Agustín/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Alagon/s/Alagon/Alagón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Albala/s/Albala/Albalá/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Alcantara/s/Alcantara/Alcántara/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Alcazar/s/Alcazar/Alcázar/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Alegria/s/Alegria/Alegría/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Alvarez/s/Alvarez/Álvarez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Alvaro/s/Alvaro/Álvaro/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/America[s | |\"|']/s/America/América/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Andalucia/s/Andalucia/Andalucía/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Andres/s/Andres/Andrés/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Angel[es| |\"|']/s/Angel/Ángel/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Antartico/s/Antartico/Antártico/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Anton[ |\"|']/s/Anton/Antón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Aragon[ |\"|'']/s/Aragon/Aragón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Artico/s/Artico/Ártico/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Atlantico/s/Atlantico/Atlántico/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Avenida España/s/Avenida España/Avenida de España/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Avenida Extremadura/s/Avenida Extremadura/Avenida de Extremadura/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Bailen[ |\"|'']/s/Bailen/Bailén/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Baltico/s/Baltico/Báltico/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Barbara/s/Barbara/Bárbara/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Bartolome/s/Bartolome/Bartolomé/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Belen/s/Belen/Belén/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Belgica/s/Belgica/Bélgica/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Berlin[ |\"|'']/s/Berlin/Berlín/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Botanico/s/Botanico/Botánico/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Calderon/s/Calderon/Calderón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Cantabrico/s/Cantabrico/Cantábrico/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Caceres/s/Caceres/Cáceres/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Caparra/s/Caparra/Cáparra/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Caparros/s/Caparros/Caparros/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Camino Fuente/s/Camino Fuente/Camino de la Fuente/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Canteria/s/Canteria/Cantería/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Capitan[ |\"|']/s/Capitan/Capitán/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Catedratico/s/Catedratico/Catedrático/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Catolicos/s/Catolicos/Católicos/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Caupolican/s/Caupolican/Caupolicán/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Ceclavin/s/Ceclavin/Ceclavín/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Cernicalo/s/Cernicalo/Cernícalo/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Cesar[ |\"|'|es]/s/Cesar/César/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Cesareo/s/Cesareo/Casáreo/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Cies/s/Cies/Cíes/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Cigueña/s/Cigueña/Cigüeña/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Colon/s/Colon/Colón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Concepcion/s/Concepcion/Concepción/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Consolacion/s/Consolacion/Consolación/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Constitucion/s/Constitucion/Constitución/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Cordoba/s/Cordoba/Córdoba/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Cortes[ |\"|']/s/Cortes/Cortés/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Critobal/s/Cristobal/Cristóbal/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Dali[ |\"|']/s/Dali/Dalí/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Diaz/s/Diaz/Díaz/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Diez/s/Diez/Díez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Dr /s/Dr/Doctor/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Dr\./s/Dr\./Doctor/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Duran[ |\"|']/s/Duran/Durán/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Espiritu/s/Espiritu/Espíritu/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Fdez/s/Fdez\.\?/Fernández/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Felix/s/Felix/Félix/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Fermin[ |\"|']/s/Fermin/Fermín/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Fernandez/s/Fernandez/Fernández/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Galan/s/Gabriel Y Galan/Gabriel y Galán/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Galan[ |\"|']/s/Galan/Galán/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Galdos/s/Galdos/Galdós/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Garcia/s/Garcia/García/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Garzon/s/Garzon/Garzón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Geminis/s/Geminis/Géminis/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/German/s/German/Germán/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Gomez/s/Gomez/Gómez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Gonzalez/s/Gonzalez/González/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Gutierrez/s/Gutierrez/Gutiérrez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Hernan[ |\"|']/s/Hernan/Hernán/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Hernandez/s/Hernandez/Hernández/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Heroes/s/Heroes/Héroes/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Hervas/s/Hervas/Hervás/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Holguin/s/Holguin/Holguín/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/iii/s/iii/III/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/ii/s/ii/II/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Ii/s/Ii/II/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Inclan/s/Inclan/Inclán/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Indico/s/Indico/Índico/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Iv/s/Iv/IV/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Ix/s/Ix/IX/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Jaraiz Vera/s/Jaraiz Vera/Jaraíz de la Vera/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Jaraiz/s/Jaraiz/Jaraíz/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Jesus/s/Jesus/Jesús/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Joaquin/s/Joaquin/Joaquín/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Jonico/s/Jonico/Jónico/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Jupiter/s/Jupiter/Júpiter/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Jose[ |\"|']/s/Jose/José/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Lain/s/Lain/Laín/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Ldo/s/Ldo\.\?/Licenciado/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Lda/s/Lda\.\?/Licenciada/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Leon[ |\"|']/s/Leon/León/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/lisboa/s/lisboa/Lisboa/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Logrosan/s/Logrosan/Logrosán/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Lopez/s/Lopez/López/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Lucia[ |\"|']/s/Lucia/Lucía/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Luis Morales/s/Luis Morales/Luis de Morales/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Mª/s/Mª/María/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Malaga/s/Malaga/Málaga/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Maria[ |\"|']/s/Maria/María/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Marmara/s/Marmara/Mármara/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Marques[ |\"|']/s/Marques/Marqués/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Marquez/s/Marquez/Márquez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Marron/s/Marron/Marrón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Martin[ |\"|']/s/Martin/Martín/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Martin/s/Martinez/Martínez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Martir/s/Martir/Mártir/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Medellin/s/Medellin/Medellín/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Medico/s/Medico/Médico/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Mediterraneo/s/Mediterraneo/Mediterráneo/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Menendez/s/Menendez/Menéndez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Merida/s/Merida/Mérida/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Millan/s/Millan/Millán/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Monfrague/s/Monfrague/Monfragüe/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Montanchez/s/Montanchez/Montánchez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Mulhacen/s/Mulhacen/Mulhacén/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Narbon[ |\"|']/s/Narbon/Narbón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Nicolas[ |\"|']/s/Nicolas/Nicolás/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Ntra/s/Ntra\.\?/Nuestra/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Oceano[ |\"|'|s]/s/Oceano/Océano/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Orion/s/Orion/Orión/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Pacifico/s/Pacifico/Pacífico/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Paris/s/Paris/París/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Paises/s/Paises/Países/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Paseo Habana/s/Paseo Habana/Paseo de La Habana/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Perez[ |\"|']/s/Perez/Pérez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Peru[ |\"|']/s/Peru/Perú/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Pinzon[ |\"|']/s/Pinzon/Pinzón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Pio[ |\"|']/s/Pio/Pío/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Plaza España/s/Plaza España/Plaza de España/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Plaza Extremadura/s/Plaza Extremadura/Plaza de Extremadura/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Pluton[ |\"|']/s/Pluton/Plutón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Prof/s/Prof\.\?/Profesor/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Primo Rivera/s/Primo Rivera/Primo de Rivera/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Principe/s/Principe/Príncipe/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Ramon[ |\"|']/s/Ramon Y Cajal/Ramón y Cajal/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Ramon[ |\"|']/s/Ramon/Ramón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Republica[ |\"|']/s/Republica/República/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Rio[ |\"|'|s]/s/Rio/Río/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Rincon[ |\"|']/s/Rincon/Rincón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Rocio/s/Rocio/Rocío/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Rodano/s/Rodano/Ródano/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Rodriguez/s/Rodriguez/Rodríguez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Roman[ |\"|']/s/Roman/Román/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Roso Luna/s/Roso Luna/Roso de Luna/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Sanchez/s/Sanchez/Sánchez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Saez/s/Saez/Sáez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Sarten[ |\"|']/s/Sarten/Sartén/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Sebastian/s/Sebastian/Sebastián/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Simon[ |\"|']/s/Simon/Simón/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Solis[ |\"|']/s/Solis/Solís/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Sra/s/Sra\.\?/Señora/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Suarez/s/Suarez/Suárez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Tamesis/s/Tamesis/Támesis/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Tenerias/s/Tenerias/Tenerías/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Tiber[ |\"|'']/s/Tiber/Tíber/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Tomas[ |\"|']/s/Tomas/Tomás/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Tortola/s/Tortola/Tórtola/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Valazquez/s/Velazquez/Velázquez/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Valdes[ |\"|']/s/Valdes/Valdés/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Xxx/s/Xxx/XXX/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Xx/s/Xx/XX/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/ Y /s/Y/y/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Zapateria/s/Zapateria/Zapatería/" result/$Poblacion/"$Poblacion""EJES.osm"
sed -i "/Zurbaran/s/Zurbaran/Zurbarán/" result/$Poblacion/"$Poblacion""EJES.osm"
